// Code generated by "stringer -type=Tag"; DO NOT EDIT

package gel

import "fmt"

const _Tag_name = "AAbbrAddressArticleAsideAudioBBdiBdoBlockquoteBodyButtonCanvasCaptionCiteCodeColgroupDataDatalistDdDelDfnDivDlDtEmFieldsetFigcaptionFigureFooterFormh1h6HeadHeaderHtmlIIframeInsKbdLabelLegendLiMainMapMarkMeterNavNoscriptObjectOlOptgroupOptionOutputPPreProgressQRbRpRtRtcRubySSampScriptSectionSelectSmallSpanStrongStyleSubSupTableTbodyTdTemplateTextareaTfootThTheadTimeTitleTrUUlVarVideoAreaBaseBrColEmbedHrImgInputKeygenLinkMetaParamSourceTrackWbr"

var _Tag_index = [...]uint16{0, 1, 5, 12, 19, 24, 29, 30, 33, 36, 46, 50, 56, 62, 69, 73, 77, 85, 89, 97, 99, 102, 105, 108, 110, 112, 114, 122, 132, 138, 144, 148, 150, 152, 156, 162, 166, 167, 173, 176, 179, 184, 190, 192, 196, 199, 203, 208, 211, 219, 225, 227, 235, 241, 247, 248, 251, 259, 260, 262, 264, 266, 269, 273, 274, 278, 284, 291, 297, 302, 306, 312, 317, 320, 323, 328, 333, 335, 343, 351, 356, 358, 363, 367, 372, 374, 375, 377, 380, 385, 389, 393, 395, 398, 403, 405, 408, 413, 419, 423, 427, 432, 438, 443, 446}

func (i Tag) String() string {
	i -= 1
	if i < 0 || i >= Tag(len(_Tag_index)-1) {
		return fmt.Sprintf("Tag(%d)", i+1)
	}
	return _Tag_name[_Tag_index[i]:_Tag_index[i+1]]
}
