// Code generated by "stringer -type=Tag"; DO NOT EDIT

package gel

import "fmt"

const _Tag_name = "AAbbrAddressArticleAsideAudioBBdiBdoBlockquoteBodyButtonCanvasCaptionCiteCodeColgroupDataDatalistDdDelDfnDivDlDtEmFieldsetFigcaptionFigureFooterFormH1H2H3H4H5H6HeadHeaderHtmlIIframeInsKbdLabelLegendLiMainMapMarkMeterNavNoscriptObjectOlOptgroupOptionOutputPPreProgressQRbRpRtRtcRubySSampScriptSectionSelectSmallSpanStrongStyleSubSupTableTbodyTdTemplateTextareaTfootThTheadTimeTitleTrUUlVarVideoAreaBaseBrColEmbedHrImgInputKeygenLinkMetaParamSourceTrackWbr"

var _Tag_index = [...]uint16{0, 1, 5, 12, 19, 24, 29, 30, 33, 36, 46, 50, 56, 62, 69, 73, 77, 85, 89, 97, 99, 102, 105, 108, 110, 112, 114, 122, 132, 138, 144, 148, 150, 152, 154, 156, 158, 160, 164, 170, 174, 175, 181, 184, 187, 192, 198, 200, 204, 207, 211, 216, 219, 227, 233, 235, 243, 249, 255, 256, 259, 267, 268, 270, 272, 274, 277, 281, 282, 286, 292, 299, 305, 310, 314, 320, 325, 328, 331, 336, 341, 343, 351, 359, 364, 366, 371, 375, 380, 382, 383, 385, 388, 393, 397, 401, 403, 406, 411, 413, 416, 421, 427, 431, 435, 440, 446, 451, 454}

func (i Tag) String() string {
	i -= 1
	if i < 0 || i >= Tag(len(_Tag_index)-1) {
		return fmt.Sprintf("Tag(%d)", i+1)
	}
	return _Tag_name[_Tag_index[i]:_Tag_index[i+1]]
}
