// Code generated by "stringer -type=Type type.go"; DO NOT EDIT.

package gel

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Textual-1]
	_ = x[Element-2]
	_ = x[Attribute-3]
	_ = x[NodeList-4]
	_ = x[AttributeList-5]
}

const _Type_name = "TextualElementAttributeNodeListAttributeList"

var _Type_index = [...]uint8{0, 7, 14, 23, 31, 44}

func (i Type) String() string {
	i -= 1
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
